/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appkant;

import appkant.Recepcionista.EncriptadorAES;
import java.awt.Color;
import java.sql.*; 
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import validador.Validador;
/**
 *
 * @author migue
 */
public class modificar extends javax.swing.JFrame {
 private Conexion conexionBD;
    private Connection conn;
    
    String usuarioID;
    public modificar(String usuarioID) {
        
       this.usuarioID = usuarioID;
        initComponents();
        cargarUsuario();
         conexionBD = new Conexion();
        try {
            conexionBD.conectar();
            conn = conexionBD.obtenerConexion(); // O puedes exponer la conexión desde tu clase
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
 public void cargarUsuario() {
    Conexion conexion = new Conexion();
    Connection conn = null;

    try {
        conexion.conectar();
        conn = conexion.getConexion();

        String sql = "SELECT u.Nombre, u.Password, u.Correo, u.Direccion, u.Telefono, u.FechaNacimiento " +
                     "FROM Usuarios u WHERE u.UsuarioID = ?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, this.usuarioID);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtNombre.setText(rs.getString("Nombre"));

            // 🔓 Desencriptar la contraseña antes de mostrarla
            String passwordEncriptada = rs.getString("Password");
            String passwordDesencriptada = EncriptadorAES.desencriptar(passwordEncriptada);
            txtContrasena.setText(passwordDesencriptada);

            txtCorreo.setText(rs.getString("Correo"));
            txtDireccion.setText(rs.getString("Direccion"));
            txtTelefono.setText(rs.getString("Telefono"));

            String fecha = rs.getString("FechaNacimiento");
            String fechaTexto = fecha;

            SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");

            try {
                java.util.Date fechaUtil = formato.parse(fechaTexto);
                java.sql.Date fechaSql = new java.sql.Date(fechaUtil.getTime());
                jdtCalendario.setDate(fechaSql);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el usuario con ese ID.");
        }

        rs.close();
        ps.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos del usuario:\n" + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    } finally {
        conexion.cerrar();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        turista = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnOjo = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jdtCalendario = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        turista.setBackground(new java.awt.Color(255, 255, 255));
        turista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario (1).png"))); // NOI18N
        turista.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 36));

        jLabel35.setFont(new java.awt.Font("Roboto SemiBold", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Modificar trabajador");
        turista.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, 30));

        jLabel37.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel37.setText("Nombre Completo");
        turista.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txtNombre.setText("Nombre y Apellidos");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        turista.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 510, 40));

        jLabel39.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel39.setText("Telefono");
        turista.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtTelefono.setText("Ej: 9516155244");
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        turista.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 510, 40));

        jLabel40.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel40.setText("Correo");
        turista.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        turista.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 510, 40));

        jLabel41.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel41.setText("Contraseña");
        turista.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel42.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel42.setText("Direccion");
        turista.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        txtDireccion.setText("Ej: ferrocarril 4");
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        turista.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 510, 40));

        jPanel16.setBackground(new java.awt.Color(48, 172, 255));
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-sd.png"))); // NOI18N
        jPanel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 66, 30));

        jLabel44.setFont(new java.awt.Font("Roboto SemiBold", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Modificar");
        jPanel16.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 150, 30));

        turista.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 1230, 50));
        turista.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 510, 40));

        btnOjo.setIcon(new javax.swing.ImageIcon("C:\\Users\\migue\\Documents\\NetBeansProjects\\AppKant\\imagen\\ojoao.jpg")); // NOI18N
        btnOjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOjoActionPerformed(evt);
            }
        });
        turista.add(btnOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 230, 50, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Regresar");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        turista.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 100, 40));

        jLabel54.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel54.setText("Fecha de nacimiento");
        turista.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        turista.add(jdtCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 510, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(turista, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(turista, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        if (txtNombre.getText().equals("Nombre y Apellidos")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if (txtNombre.getText().trim().equals("")) {
            txtNombre.setText("Nombre y Apellidos");
            txtNombre.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
    if (!Character.isLetter(c) && c != ' ') {
        evt.consume(); // Bloquea cualquier carácter que no sea letra o espacio
    }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained
        if (txtTelefono.getText().equals("Ej: 9516155244")) {
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        if (txtTelefono.getText().trim().equals("")) {
            txtTelefono.setText("Ej: 9516155244");
            txtTelefono.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        if (txtCorreo.getText().equals("Ej: kickgara16423@gmail.com")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if (txtCorreo.getText().trim().equals("")) {
            txtCorreo.setText("Ej: kickgara16423@gmail.com");
            txtCorreo.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusGained
        if (txtDireccion.getText().equals("Ej: ferrocarril 4")) {
            txtDireccion.setText("");
            txtDireccion.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDireccionFocusGained

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        if (txtDireccion.getText().trim().equals("")) {
            txtDireccion.setText("Ej: ferrocarril 4");
            txtDireccion.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
 String nombre = txtNombre.getText().trim();
String contrasena = new String(txtContrasena.getPassword()).trim();
String telefono = txtTelefono.getText().trim();
String correo = txtCorreo.getText().trim();
String direccion = txtDireccion.getText().trim();
java.util.Date fec = jdtCalendario.getDate();
String fechao = "";

if (fec != null) {
    SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    fechao = formato.format(fec);
}

if (nombre.isEmpty() || correo.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || contrasena.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
} else if (!Validador.validarCorreo(correo.trim())) {
    JOptionPane.showMessageDialog(null, "Debe dar un correo real", "", JOptionPane.ERROR_MESSAGE);
} else if (!Validador.validarContrasena(contrasena)) {
    JOptionPane.showMessageDialog(null, "La contraseña tiene que ser de 8 carácteres", "", JOptionPane.ERROR_MESSAGE);
} else if (fec == null) {
    JOptionPane.showMessageDialog(null, "Falta elegir la fecha, aún no se ha seleccionado.", "Fecha requerida", JOptionPane.WARNING_MESSAGE);
} else {
    int confirm = JOptionPane.showConfirmDialog(null, "¿Estás seguro de modificar al trabajador?", "Confirmar modificación", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    Conexion conexion = new Conexion();
    Connection conn = null;

    try {
        conexion.conectar();
        conn = conexion.getConexion();

        String sql1 = "UPDATE Usuarios SET Nombre = ?, Correo = ?, Password = ?, Direccion = ?, Telefono = ?, FechaNacimiento = ? WHERE UsuarioID = ?";
        PreparedStatement stmt1 = conn.prepareStatement(sql1);

        stmt1.setString(1, nombre);
        stmt1.setString(2, correo);

        // 🔐 Encriptar la contraseña antes de guardarla
        String contrasenaEncriptada = EncriptadorAES.encriptar(contrasena);
        stmt1.setString(3, contrasenaEncriptada);

        stmt1.setString(4, direccion);
        stmt1.setString(5, telefono);
        stmt1.setString(6, fechao);
        stmt1.setString(7, this.usuarioID);

        stmt1.executeUpdate();
        stmt1.close();

        JOptionPane.showMessageDialog(null, "Usuario modificado exitosamente.");

        Recepcionista recepcionista = new Recepcionista();
        recepcionista.setVisible(true);
        this.dispose();

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al modificar usuario:\n" + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    } finally {
        conexion.cerrar();
    }
}

    }//GEN-LAST:event_jPanel16MouseClicked

    private void btnOjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOjoActionPerformed
        // TODO add your handling code here:

        if(btnOjo.isSelected()){
           btnOjo.setIcon(new javax.swing.ImageIcon("imagen/ojoco.jpg"));

            txtContrasena.setEchoChar((char)0);

        }else{
          btnOjo.setIcon(new javax.swing.ImageIcon("imagen/ojoao.jpg"));
            txtContrasena.setEchoChar('*');
        }
    }//GEN-LAST:event_btnOjoActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
   int confirm = JOptionPane.showConfirmDialog(null,
            "¿Estás seguro de que deseas regresar?, los cambios no serán guardados",
            "Confirmación", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;
        
Recepcionista n=new Recepcionista();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume(); // Cancela el evento, no permite la tecla
    }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String usuarioID=null;
                new modificar(usuarioID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnOjo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel16;
    private com.toedter.calendar.JDateChooser jdtCalendario;
    private javax.swing.JPanel turista;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
