/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appkant;

import java.io.File;
import javax.swing.JOptionPane;
import java.sql.*; 
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author migue
 */
public class modificarplan extends javax.swing.JFrame {
 private Conexion conexionBD;
    private Connection conn;
    /**
     * Creates new form modificarplan
     */
     String nom;
    public modificarplan(String nom) {
      
        initComponents();
          this.nom=nom;
         cargarPlan();
         txtPrecio1.setEditable(false); 
    }
    private File imagenSeleccionada = null;

 public void cargarPlan() {
  Conexion conexion = new Conexion();
    Connection conn = null;

    try {
        conexion.conectar();
        conn = conexion.getConexion();

        String sql = "SELECT descripcion, precio , imagen FROM Planes WHERE nombre = ?" ;
                     
                   

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, this.nom);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtNombre.setText(nom);
            txtDescripcion.setText(rs.getString("Descripcion"));
            txtPrecio.setText(rs.getString("precio"));
            txtPrecio1.setText(rs.getString("imagen"));
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el usuario con ese ID.");
        }

        rs.close();
        ps.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos del usuario:\n" + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    } finally {
        conexion.cerrar();
    }
       
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        turista1 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        turista1.setBackground(new java.awt.Color(255, 255, 255));
        turista1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Roboto SemiBold", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Registro de Plan turístico");
        turista1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 403, 30));

        jLabel50.setForeground(new java.awt.Color(102, 102, 102));
        jLabel50.setText("Ingresa los datos del nuevo turista");
        turista1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel51.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel51.setText("Nombre del plan");
        turista1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        turista1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 510, 40));

        jLabel52.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel52.setText("Descripción");
        turista1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        txtDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescripcionFocusLost(evt);
            }
        });
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        turista1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 510, 40));

        jLabel53.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel53.setText("Ubicacion de imagen:");
        turista1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        turista1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 510, 40));

        jPanel17.setBackground(new java.awt.Color(48, 172, 255));
        jPanel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-sd.png"))); // NOI18N
        jPanel17.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 66, 30));

        jLabel68.setFont(new java.awt.Font("Roboto SemiBold", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Modificar");
        jPanel17.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 150, 30));

        turista1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 1230, 50));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Regresar");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        turista1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 90, 40));

        jLabel54.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel54.setText("Precio");
        turista1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtPrecio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecio1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecio1FocusLost(evt);
            }
        });
        txtPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecio1ActionPerformed(evt);
            }
        });
        turista1.add(txtPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 510, 40));

        jButton3.setText("Elegir imagen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        turista1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 220, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(turista1, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(turista1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripcionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionFocusGained

    private void txtDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripcionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionFocusLost

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioFocusGained

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioFocusLost

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
 String nombre=txtNombre.getText();
 String precio=txtPrecio.getText();
 String descripcion=txtDescripcion.getText();
 String imagen=txtPrecio1.getText();
        
        
        if (nombre.isEmpty() || precio.isEmpty() || descripcion.isEmpty() || imagen.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
        return;
    }
         int confirm = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que desa modificar el plan?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) return;

         Conexion conexion = new Conexion();
    Connection conn = null;
 try {
        conexion.conectar();
        conn = conexion.getConexion();

        
        String sql1 = "UPDATE Planes SET precio = ?,descripcion=?,imagen=? WHERE nombre = ?";
        PreparedStatement stmt1 = conn.prepareStatement(sql1);
        stmt1.setString(1, precio);
        stmt1.setString(2, descripcion);
         stmt1.setString(3, imagen);
        stmt1.setString(4, nom); 
        
        stmt1.executeUpdate();
        stmt1.close();

       
        String sql2 = "UPDATE Planes SET nombre = ? WHERE precio = ? AND descripcion=?";
        PreparedStatement stmt2 = conn.prepareStatement(sql2);
        stmt2.setString(1, nombre);
        stmt2.setString(2, precio);
        stmt2.setString(3, descripcion);
       
        stmt2.executeUpdate();
        stmt2.close();

        JOptionPane.showMessageDialog(null, "Plan modificado exitosamente.");
        
        
        Recepcionista recepcionista = new Recepcionista();
        recepcionista.setVisible(true);
        this.dispose();

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al modificar usuario:\n" + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    } finally {
        conexion.cerrar();
    }       
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
   int confirm = JOptionPane.showConfirmDialog(null,
            "¿Estás seguro de que deseas regresar?, los cambios no serán guardados",
            "Confirmación", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;
        
        Recepcionista n=new Recepcionista();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtPrecio1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecio1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1FocusGained

    private void txtPrecio1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecio1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1FocusLost

    private void txtPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.setVisible(true);
        chooser.setDialogTitle("Selecciona una imagen");

        FileNameExtensionFilter filtro = new FileNameExtensionFilter(
            "Imágenes (jpg, jpeg, png, gif)", "jpg", "jpeg", "png", "gif");
        chooser.setFileFilter(filtro);

        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            if (archivo != null && archivo.isFile()) {
                imagenSeleccionada = archivo;

                // Asegúrate de que txtRuta existe y es un JTextField (o bórralo si no lo usas)
                txtPrecio1.setText(archivo.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(this,
                    "No se seleccionó un archivo válido",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarplan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 String nom=null;
                new modificarplan(nom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel turista1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio1;
    // End of variables declaration//GEN-END:variables
}
