/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appkant;
import validador.Validador;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import com.github.lgooddatepicker.components.DatePicker;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.List;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.SecureRandom;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.border.AbstractBorder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.UUID;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;

import java.awt.Color;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

/**
 *
 * @author migue
 */
public class RegistroUsuario extends javax.swing.JFrame {
private Conexion conexionBD;
    private Connection conn;
    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
     initComponents();
        conexionBD = new Conexion();
        try {
            conexionBD.conectar();
            conn = conexionBD.obtenerConexion(); 
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        turista = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        turistaNombre = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        turistaUser = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        turistaTel = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        turistaEmail = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        turistaAdress = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        pan = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jdtCalendario = new com.toedter.calendar.JDateChooser();
        btnOjo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        turista.setBackground(new java.awt.Color(255, 255, 255));
        turista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario (1).png"))); // NOI18N
        turista.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 36));

        jLabel35.setFont(new java.awt.Font("Roboto SemiBold", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Registro de Turista");
        turista.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 403, 30));

        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Ingresa los datos del nuevo turista");
        turista.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel37.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel37.setText("Nombre Completo");
        turista.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        turistaNombre.setText("Nombre y Apellidos");
        turistaNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                turistaNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                turistaNombreFocusLost(evt);
            }
        });
        turistaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turistaNombreMouseClicked(evt);
            }
        });
        turistaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turistaNombreActionPerformed(evt);
            }
        });
        turistaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                turistaNombreKeyTyped(evt);
            }
        });
        turista.add(turistaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 510, 40));

        jLabel38.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel38.setText("Contraseña");
        turista.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        turistaUser.setText("Ej: juanito16_6");
        turistaUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                turistaUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                turistaUserFocusLost(evt);
            }
        });
        turistaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turistaUserActionPerformed(evt);
            }
        });
        turista.add(turistaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 510, 40));

        jLabel39.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel39.setText("Telefono");
        turista.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        turistaTel.setText("Ej: 9516155244");
        turistaTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                turistaTelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                turistaTelFocusLost(evt);
            }
        });
        turistaTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turistaTelActionPerformed(evt);
            }
        });
        turista.add(turistaTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 510, 40));

        jLabel40.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel40.setText("Correo");
        turista.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        turistaEmail.setText("Ej: javi.nomag16423@gmail.com");
        turistaEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                turistaEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                turistaEmailFocusLost(evt);
            }
        });
        turistaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turistaEmailActionPerformed(evt);
            }
        });
        turista.add(turistaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 510, 40));

        jLabel41.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel41.setText("Fecha de nacimiento");
        turista.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel42.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel42.setText("Direccion");
        turista.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        turistaAdress.setText("Ej: ferrocarril 4");
        turistaAdress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                turistaAdressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                turistaAdressFocusLost(evt);
            }
        });
        turistaAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turistaAdressActionPerformed(evt);
            }
        });
        turista.add(turistaAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 510, 40));

        jPanel16.setBackground(new java.awt.Color(48, 172, 255));
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-sd.png"))); // NOI18N
        jPanel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 66, 30));

        jLabel44.setFont(new java.awt.Font("Roboto SemiBold", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Guardar Turista");
        jPanel16.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 150, 30));

        turista.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 1230, 50));

        jLabel45.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel45.setText("Usuario");
        turista.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));
        turista.add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 410, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("x");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        turista.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));
        turista.add(jdtCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 520, 40));

        btnOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appkant/ojoao.jpg"))); // NOI18N
        btnOjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOjoActionPerformed(evt);
            }
        });
        turista.add(btnOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(turista, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(turista, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void turistaNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaNombreFocusGained
        if (turistaNombre.getText().equals("Nombre y Apellidos")) {
            turistaNombre.setText("");
            turistaNombre.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_turistaNombreFocusGained

    private void turistaNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaNombreFocusLost
        if (turistaNombre.getText().trim().equals("")) {
            turistaNombre.setText("Nombre y Apellidos");
            turistaNombre.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_turistaNombreFocusLost

    private void turistaNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turistaNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_turistaNombreMouseClicked

    private void turistaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turistaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turistaNombreActionPerformed

    private void turistaUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaUserFocusGained
        if (turistaUser.getText().equals("Ej: juanito16_6")) {
            turistaUser.setText("");
            turistaUser.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_turistaUserFocusGained

    private void turistaUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaUserFocusLost
        if (turistaUser.getText().trim().equals("")) {
            turistaUser.setText("Ej: juanito16_6");
            turistaUser.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_turistaUserFocusLost

    private void turistaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turistaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turistaUserActionPerformed

    private void turistaTelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaTelFocusGained
        if (turistaTel.getText().equals("Ej: 9516155244")) {
            turistaTel.setText("");
            turistaTel.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_turistaTelFocusGained

    private void turistaTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaTelFocusLost
        if (turistaTel.getText().trim().equals("")) {
            turistaTel.setText("Ej: 9516155244");
            turistaTel.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_turistaTelFocusLost

    private void turistaTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turistaTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turistaTelActionPerformed

    private void turistaEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaEmailFocusGained
        if (turistaEmail.getText().equals("Ej: javi.nomag16423@gmail.com")) {
            turistaEmail.setText("");
            turistaEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_turistaEmailFocusGained

    private void turistaEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaEmailFocusLost
        if (turistaEmail.getText().trim().equals("")) {
            turistaEmail.setText("Ej: javi.nomag16423@gmail.com");
            turistaEmail.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_turistaEmailFocusLost

    private void turistaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turistaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turistaEmailActionPerformed

    private void turistaAdressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaAdressFocusGained
        if (turistaAdress.getText().equals("Ej: ferrocarril 4")) {
            turistaAdress.setText("");
            turistaAdress.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_turistaAdressFocusGained

    private void turistaAdressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turistaAdressFocusLost
        if (turistaAdress.getText().trim().equals("")) {
            turistaAdress.setText("Ej: ferrocarril 4");
            turistaAdress.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_turistaAdressFocusLost

    private void turistaAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turistaAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turistaAdressActionPerformed

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
        
        String usuarioID = generarID();
         String contra = new String(pan.getPassword()).trim();
        String fechao=""; 
         Date fecha = jdtCalendario.getDate();


 if (fecha != null) {
      SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    fechao = sdf.format(fecha);
}
 
/*
         Validador.validarCamposLlenos(turistaUser.getText().trim(),contra, turistaNombre.getText().trim(),
               turistaTel.getText().trim(),turistaEmail.getText().trim(),contrapas.getText().trim(),turistaAdress.getText().trim())==false
         */         
 if(     Validador.validarCamposLlenos(turistaUser.getText().trim(),contra, turistaNombre.getText().trim(),
               turistaTel.getText().trim(),turistaEmail.getText().trim(),fechao,turistaAdress.getText().trim())==false
         ){
     JOptionPane.showMessageDialog(null,
            "Todos los campos deben que estar llenos" ,
            "",
            JOptionPane.ERROR_MESSAGE);
    }else if(Validador.validarCorreo(turistaEmail.getText().trim())==false ){
            JOptionPane.showMessageDialog(null,
            "Debe dar un correo real" ,
            "",
            JOptionPane.ERROR_MESSAGE);}
    else if(Validador.validarContrasena(contra)==false){
    JOptionPane.showMessageDialog(null,
            "La contraseña tiene que ser de 8 carácteres" ,
            "",
            JOptionPane.ERROR_MESSAGE);
    }else if (fecha == null) {
   
    JOptionPane.showMessageDialog(null, "Falta elegir la fecha, aún no se ha seleccionado.", "Fecha requerida", JOptionPane.WARNING_MESSAGE);
}else{
                
     // Correo remitente y clave de aplicación
    final String remitente = "kantkickgarabatoinc@gmail.com";
    final String clave = "lqrx slza fgij gmwu";

    // Correo destinatario
    String destinatario =turistaEmail.getText().trim();
System.out.println("Correo destinatario:" + destinatario);

    // Asunto y cuerpo del mensaje
    String asunto = "Bienvenido a KANT ";
    String cuerpo = "Bienvenido a KANT turista";

    // Ruta al archivo adjunto - ¡ESCRITA BIEN Y SIN CARACTERES RAROS!
    String archivoRuta = "C:\\Users\\migue\\Documents\\NetBeansProjects\\AppKant\\documentob.pdf";

    // Opcional: imprime ruta para depuración
    System.out.println("Ruta archivo: [" + archivoRuta + "]");

    Properties props = new Properties();
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "587");
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.starttls.enable", "true");

    Session session = Session.getInstance(props, new javax.mail.Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(remitente, clave);
        }
    });

    try {
        Message message = new MimeMessage(session);
        message.setFrom(new InternetAddress(remitente));
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(destinatario));
        message.setSubject(asunto);

        MimeBodyPart texto = new MimeBodyPart();
        texto.setText(cuerpo);

        MimeBodyPart adjunto = new MimeBodyPart();
        File archivo = new File(archivoRuta);

        if (!archivo.exists()) {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado en: " + archivo.getCanonicalPath());
            return;
        }

        adjunto.attachFile(archivo);

        Multipart multiParte = new MimeMultipart();
        multiParte.addBodyPart(texto);
        multiParte.addBodyPart(adjunto);

        message.setContent(multiParte);
        
        
        System.out.println("Enviando correo a: " + destinatario);
System.out.println("Desde: " + remitente);
System.out.println("Asunto: " + asunto);
System.out.println("Cuerpo: " + cuerpo);

        Transport.send(message);

        JOptionPane.showMessageDialog(null, "Correo enviado correctamente");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al enviar: " + e.getMessage());
        e.printStackTrace();
    }
        
        
        
        guardarTurista(
            usuarioID,
            turistaUser.getText().trim(),
            contra,
            turistaNombre.getText().trim(),
            turistaTel.getText().trim(),
            turistaEmail.getText().trim(),
           fechao,
            turistaAdress.getText().trim()
        ); 




    }
    }//GEN-LAST:event_jPanel16MouseClicked

   

    
    
    
    
    
    
    
    
    
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Usuario n=new Usuario();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void turistaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_turistaNombreKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c)){
        evt.consume();
        }
    }//GEN-LAST:event_turistaNombreKeyTyped

    private void btnOjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOjoActionPerformed
        // TODO add your handling code here:
        
        if(btnOjo.isSelected()){
      btnOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ojoco.jpg")));
               
        pan.setEchoChar((char)0);
        
        }else{
        btnOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ojoao.jpg")));
         pan.setEchoChar('*');
        }
    }//GEN-LAST:event_btnOjoActionPerformed
public void guardarTurista(String usuarioID, String claveUsuario, String password, String nombre,
                           String telefono, String correo, String fechaNacimiento, String direccion) {
    Conexion conexion = new Conexion();
    Connection conn = null;

    try {
        conexion.conectar();
        conn = conexion.getConexion();
        conn.setAutoCommit(false);

       
        String sqlUsuarios = "INSERT INTO Usuarios (UsuarioID, ClaveUsuario, Password, Nombre, Estatus, rolID) " +
                             "VALUES (?, ?, ?, ?, 'activo', '3')";
        try (PreparedStatement stmt = conn.prepareStatement(sqlUsuarios)) {
            stmt.setString(1, usuarioID);
            stmt.setString(2, claveUsuario);
            stmt.setString(3, password);
            stmt.setString(4, nombre);
            stmt.executeUpdate();
        }

       
        String sqlContactos = "INSERT INTO Contactos (UsuarioID, Telefono, Correo, FechaNacimiento, FechaReg, Direccion) " +
                              "VALUES (?, ?, ?, ?, date('now'), ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sqlContactos)) {
            stmt.setString(1, usuarioID);
            stmt.setString(2, telefono);
            stmt.setString(3, correo);
            stmt.setString(4, fechaNacimiento);
            stmt.setString(5, direccion);
            stmt.executeUpdate();
        }

        conn.commit();
        JOptionPane.showMessageDialog(null, "Turista registrado con éxito.");

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null,
            "Error al registrar turista:\n" + e.getMessage(),
            "Error SQL",
            JOptionPane.ERROR_MESSAGE);
        try {
            if (conn != null) conn.rollback();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,
                "Error al hacer rollback:\n" + ex.getMessage(),
                "Error crítico",
                JOptionPane.ERROR_MESSAGE);
        }
    } finally {
        conexion.cerrar();
    }
} 
  public static String generarID() {
    String caracteres = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    SecureRandom random = new SecureRandom();
    StringBuilder sb = new StringBuilder(8); // longitud
    for (int i = 0; i < 8; i++) {
        sb.append(caracteres.charAt(random.nextInt(caracteres.length())));
    }
    return "UK_" + sb.toString();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnOjo;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel16;
    private com.toedter.calendar.JDateChooser jdtCalendario;
    private javax.swing.JPasswordField pan;
    private javax.swing.JPanel turista;
    private javax.swing.JTextField turistaAdress;
    private javax.swing.JTextField turistaEmail;
    private javax.swing.JTextField turistaNombre;
    private javax.swing.JTextField turistaTel;
    private javax.swing.JTextField turistaUser;
    // End of variables declaration//GEN-END:variables
}
